### PR TITLE
Upstream 0.3.0 release

### PR DESCRIPTION
**Pull request by rmnvgr**
This PR does the following:
- Update OpenRCT2 to v0.3.0 and objects to v1.0.16, change title sequences install directory
- Remove the Appdata release patch (fixed upstream)
- Build Duktape library to support plugins
- Export additional desktop files for savegames, scenarios and URIs MIME support
- Change CMake build type to `RelWithDebInfo`

Let me know if that looks good to you.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, that all looks good to me. I still don't have the game data files (I own the game on CD, but the CD isn't in the same place as me at the moment), so can I assume you have built this and taken it for a test drive?

**Comment by rmnvgr** [comment]
Yes, I've tested it on my machine and everything I checked (new scenario, loading savegame, multiplayer, RCT1 scenarios) work as expected.

**Comment by takluyver** [comment]
Thanks!

BTW, were you already invited to help maintain this repo? I don't think I can give you access myself, but if you ping the flathub maintainers they should be able to help.

**Comment by rmnvgr** [comment]
Done, thank you!

**Pull request merged**
